site_name: Xolmis User Manual
site_url: ""
use_directory_urls: false
repo_url: https://github.com/cbeier-studio/Xolmis
site_author: Christian Beier
copyright: Copyright &copy; 2024-2025 Christian Beier
nav:
  - Home: index.md
  - About Xolmis:
    - Introduction: introduction.md
    - Release Notes: release-notes.md
    - FAQ: faq.md
    - Best Practices: best-practices.md
    - Xolmis Mobile: xolmis-mobile.md
    - Glossary: glossary.md
    - Feedback: feedback.md
    - Sponsors: sponsors.md
    - Privacy Policy: privacy.md
    - License: license.md
    - Third-Party Notices: third-party.md
  - Getting Started:
    - Installing: installing.md
    - Starting a new database: first-steps.md
    - Connections: connections.md
    - Users: users.md
    - Settings: settings.md
  - Using Xolmis:
    - User interface: interface.md
    - Keyboard shortcuts: shortcuts.md
    - Adding and editing data: adding-and-editing-data.md
    - Search and filtering data: search-and-filtering-data.md
    - Exporting data: exporting-data.md
    - Importing data: importing-data.md
    - Images: images.md
    - Audio recordings: audio-recordings.md
    - Videos: videos.md
    - Documents and links: documents.md
    - Map: map.md
    - Summary: summary.md
    - Record verifications: record-verifications.md
    - Record history: record-history.md
    - Print data: print-data.md
    - Maintenance: maintenance.md
  - Modules:
    - Geo:
      - Gazetteer: gazetteer.md
      - Sampling plots: sampling-plots.md
      - Coordinates converter: coordinates-converter.md
    - Management:
      - Institutions: institutions.md
      - Researchers: researchers.md
      - Projects: projects.md
      - Permits: permits.md
      - Bands: bands.md
    - Fieldwork:
      - Methods: methods.md
      - Expeditions: expeditions.md
      - Surveys: surveys.md
      - Sightings: sightings.md
      - Specimens: specimens.md
      - Individuals: individuals.md
      - Captures: captures.md
      - Feathers: feathers.md
      - Nests: nests.md
      - Eggs: eggs.md
    - Taxonomy:
      - Botanical taxa: botanical-taxa.md
      - Taxa: taxa.md
theme:
  name: material
  logo: img/xolmis-icon.png
  language: en
  features:
    - search.highlight
    - search.suggest
markdown_extensions: 
  - abbr
  - admonition
  - codehilite
  - footnotes
  - def_list
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins: 
  - search
  - badges
  - offline
  - tags
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt
          name: Português
          build: true
          site_name: "Manual do Usuário do Xolmis"
          nav:
            - Home: index.md
            - Sobre o Xolmis:
              - Introdução: introduction.md
              - Notas de versão: release-notes.md
              - FAQ: faq.md
              - Boas práticas: best-practices.md
              - Xolmis Mobile: xolmis-mobile.md
              - Glossário: glossary.md
              - Feedback: feedback.md
              - Patrocinadores: sponsors.md
              - Política de privacidade: privacy.md
              - Licença: license.md
              - Aviso de terceiros: third-party.md
            - Primeiros passos:
              - Instalando: installing.md
              - Iniciando um novo banco de dados: first-steps.md
              - Conexões: connections.md
              - Usários: users.md
              - Configurações: settings.md
            - Usando o Xolmis:
              - Interface de usuário: interface.md
              - Atalhos de teclado: shortcuts.md
              - Adicionando e editando dados: adding-and-editing-data.md
              - Busca e filtragem de dados: search-and-filtering-data.md
              - Exportando dados: exporting-data.md
              - Importando dados: importing-data.md
              - Imagens: images.md
              - Gravações de áudio: audio-recordings.md
              - Vídeos: videos.md
              - Documentos e links: documents.md
              - Mapa: map.md
              - Resumo: summary.md
              - Verificações do registro: record-verifications.md
              - Histórico do registro: record-history.md
              - Imprimir dados: print-data.md
              - Manutenção: maintenance.md
            - Módulos:
              - Geo:
                - Gazetteer: gazetteer.md
                - Parcelas amostrais: sampling-plots.md
                - Conversor de coordenadas: coordinates-converter.md
              - Gestão:
                - Instituições: institutions.md
                - Pesquisadores: researchers.md
                - Projetos: projects.md
                - Licenças: permits.md
                - Anilhas: bands.md
              - Trabalho de campo:
                - Métodos: methods.md
                - Expedições: expeditions.md
                - Amostragens: surveys.md
                - Observações: sightings.md
                - Espécimes: specimens.md
                - Indivíduos: individuals.md
                - Capturas: captures.md
                - Penas: feathers.md
                - Ninhos: nests.md
                - Ovos: eggs.md
              - Taxonomia:
                - Táxons botânicos: botanical-taxa.md
                - Táxons: taxa.md